### ISSUE TITLE
Failed tests upon clean checkout

### ISSUE THREAD

**Issue by MEnnabah** [apple/swift#60885]
**Describe the bug**
Post checkout, I built using Ninja and passed `--test` flag. This resulted in the following failed tests:

```
Failed Tests (4):
  Swift(macosx-arm64) :: Interop/Cxx/class/inheritance/fields.swift
  Swift(macosx-arm64) :: Interop/Cxx/class/inheritance/functions.swift
  Swift(macosx-arm64) :: Interop/Cxx/foreign-reference/pod.swift
  Swift(macosx-arm64) :: Interop/Cxx/operators/member-inline.swift
```

**Steps To Reproduce**
1. Follow the steps described in [Cloning the project](https://github.com/apple/swift/blob/main/docs/HowToGuides/GettingStarted.md#cloning-the-project).
2. At the time of raising this issue, the `main` branch is pointing at commit `15e17b2`.
3. Build via Ninja (notice the `--test` flag)
```
utils/build-script --skip-build-benchmarks \
  --skip-ios --skip-watchos --skip-tvos --swift-darwin-supported-archs "$(uname -m)" \
  --sccache --release-debuginfo --swift-disable-dead-stripping --test
```

**Expected behavior**
All tests passes.

**Environment (please fill out the following information)**
 - OS: macOS 12.3
 - Xcode 13.4

**Additional context**
Full build logs

```
Failed Tests (4):
  Swift(macosx-arm64) :: Interop/Cxx/class/inheritance/fields.swift
  Swift(macosx-arm64) :: Interop/Cxx/class/inheritance/functions.swift
  Swift(macosx-arm64) :: Interop/Cxx/foreign-reference/pod.swift
  Swift(macosx-arm64) :: Interop/Cxx/operators/member-inline.swift


Testing Time: 578.24s
  Unsupported      :  486
  Passed           : 8412
  Expectedly Failed:   24
  Failed           :    4

4 warning(s) in tests
FAILED: test/CMakeFiles/check-swift-macosx-arm64 /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/test/CMakeFiles/check-swift-macosx-arm64
cd /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/test && /opt/homebrew/Cellar/cmake/3.24.1/bin/cmake -E remove_directory /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/./swift-test-results/arm64-apple-macosx10.9 && /opt/homebrew/Cellar/cmake/3.24.1/bin/cmake -E make_directory /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/./swift-test-results/arm64-apple-macosx10.9 && /opt/homebrew/Cellar/cmake/3.24.1/bin/cmake -E env /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Users/mennabah/projects/os/swift-project/llvm-project/llvm/utils/lit/lit.py --param bootstrapping_mode=BOOTSTRAPPING-WITH-HOSTLIBS -sv -j 10 --xunit-xml-output=/Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/./swift-test-results/arm64-apple-macosx10.9/lit-tests.xml --param differentiable_programming --param concurrency --param distributed --param string_processing --param threading=darwin --param swift_test_subset=primary --param swift_test_mode=optimize_none /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/test-macosx-arm64
ninja: build stopped: subcommand failed.
ERROR: command terminated with a non-zero exit status 1, aborting
```

**Comment by buttaface** [comment]
That's not a full build log, you'll want to show the actual errors. [The Apple Silicon CI doesn't show these failures](https://ci.swift.org/job/oss-swift-incremental-RA-macos-apple-silicon/), so they were probably subsequently fixed by other C++ Interoperability pulls, as there is a lot of work ongoing there now.

I suggest you update to the latest commit and see if you can reproduce now.

**Comment by MEnnabah** [comment]
Ah that's weird I'm getting these failed tests locally, I'll need to do more research on that.
However, I've updated to a more recent commit (the latest at that time), and I can still see they're failing.

Commit:
```bash
$ echo $(git log -n1 --format="%h")                                                                                                                                                                   
86e633197d9
```
Here's a complete stacktrace for the failure:

```
******************** 
TEST 'Swift(macosx-arm64) :: Interop/Cxx/class/inheritance/fields.swift' FAILED 
********************
Assertion failed: (wrapperModule && "CxxShim module is required when using members of a base class. " "Make sure you `import CxxShim`."), function getInteropStaticCastDeclRefExpr, file ClangImporter.cpp, line 4423.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.	Program arguments: /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend -frontend -c -primary-file /Users/mennabah/projects/os/swift-project/swift/test/Interop/Cxx/class/inheritance/fields.swift -target arm64-apple-macosx10.9 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -I /Users/mennabah/projects/os/swift-project/swift/test/Interop/Cxx/class/inheritance/Inputs/ -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -F /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/lib -module-cache-path /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/swift-test-results/arm64-apple-macosx10.9/clang-module-cache -swift-version 4 -define-availability "SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999" -define-availability "SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2" -define-availability "SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0" -define-availability "SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4" -define-availability "SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0" -define-availability "SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5" -define-availability "SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0" -define-availability "SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4" -define-availability "SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0" -define-availability "SwiftStdlib 5.8:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999" -enable-experimental-cxx-interop -target-sdk-version 12.3 -module-name main -o /var/folders/7f/4610pvjn35j3qs7cjyzzqhjc0000gn/T/lit-tmp-lcqs5pss/fields-30259a.o
1.	Swift version 5.8-dev (LLVM c87bb6a98117a76, Swift 86e633197d96169)
2.	Compiling with effective version 4.1.50
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for file "/Users/mennabah/projects/os/swift-project/swift/test/Interop/Cxx/class/inheritance/fields.swift")
4.	While silgen emitFunction SIL function "@$sSo14DerivedFromAllV1as5Int32Vvg".
 for getter for a (in module 'Fields')
5.	While evaluating request TypeCheckFunctionBodyRequest(Fields.(file).DerivedFromAll._)
6.	While evaluating request ParseAbstractFunctionBodyRequest(Fields.(file).DerivedFromAll._)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000105bfba48 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000105bfac3c llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x0000000105bfc090 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000019b5c14c4 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000019b5a9ee0 pthread_kill + 288
5  libsystem_c.dylib        0x000000019b4e4340 abort + 168
6  libsystem_c.dylib        0x000000019b4e3754 err + 0
7  swift-frontend           0x000000010611ef2c getInteropStaticCastDeclRefExpr(swift::ASTContext&, clang::Module const*, swift::Type, swift::Type) (.cold.4) + 0
8  swift-frontend           0x0000000101de68d8 getInteropStaticCastDeclRefExpr(swift::ASTContext&, clang::Module const*, swift::Type, swift::Type) + 524
9  swift-frontend           0x0000000101def530 synthesizeBaseClassFieldGetterBody(swift::AbstractFunctionDecl*, void*) + 392
10 swift-frontend           0x0000000102256fa0 swift::ParseAbstractFunctionBodyRequest::evaluate(swift::Evaluator&, swift::AbstractFunctionDecl*) const + 304
11 swift-frontend           0x0000000102058a58 llvm::Expected<swift::ParseAbstractFunctionBodyRequest::OutputType> swift::Evaluator::getResultUncached<swift::ParseAbstractFunctionBodyRequest>(swift::ParseAbstractFunctionBodyRequest const&) + 380
12 swift-frontend           0x000000010205878c llvm::Expected<swift::ParseAbstractFunctionBodyRequest::OutputType> swift::Evaluator::getResultCached<swift::ParseAbstractFunctionBodyRequest, (void*)0>(swift::ParseAbstractFunctionBodyRequest const&) + 100
13 swift-frontend           0x0000000101fbd6d4 swift::ParseAbstractFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::ParseAbstractFunctionBodyRequest>(swift::Evaluator&, swift::ParseAbstractFunctionBodyRequest, swift::ParseAbstractFunctionBodyRequest::OutputType) + 40
14 swift-frontend           0x0000000101f9f81c swift::AbstractFunctionDecl::getBody(bool) const + 196
15 swift-frontend           0x0000000101b8bbe0 swift::TypeCheckFunctionBodyRequest::evaluate(swift::Evaluator&, swift::AbstractFunctionDecl*) const + 184
16 swift-frontend           0x000000010205a604 llvm::Expected<swift::TypeCheckFunctionBodyRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckFunctionBodyRequest>(swift::TypeCheckFunctionBodyRequest const&) + 376
17 swift-frontend           0x000000010205a3cc llvm::Expected<swift::TypeCheckFunctionBodyRequest::OutputType> swift::Evaluator::getResultCached<swift::TypeCheckFunctionBodyRequest, (void*)0>(swift::TypeCheckFunctionBodyRequest const&) + 104
18 swift-frontend           0x0000000101fbd830 swift::TypeCheckFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckFunctionBodyRequest>(swift::Evaluator&, swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType) + 36
19 swift-frontend           0x000000010140f52c swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) + 140
20 swift-frontend           0x000000010139bee8 swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 6812
21 swift-frontend           0x00000001013a04a0 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 4168
22 swift-frontend           0x000000010144d908 swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> > (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 132
23 swift-frontend           0x00000001013a3adc llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::getResultUncached<swift::ASTLoweringRequest>(swift::ASTLoweringRequest const&) + 380
24 swift-frontend           0x00000001013a0784 swift::performASTLowering(swift::FileUnit&, swift::Lowering::TypeConverter&, swift::SILOptions const&, swift::IRGenOptions const*) + 80
25 swift-frontend           0x0000000100dfc2a0 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 520
26 swift-frontend           0x0000000100e0ae6c withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
27 swift-frontend           0x0000000100dfdfb0 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3248
28 swift-frontend           0x0000000100c6c884 swift::mainEntry(int, char const**) + 3144
29 dyld                     0x0000000119471088 start + 516
<unknown>:0: error: unable to execute command: Abort trap: 6
<unknown>:0: error: compile command failed due to signal 6 (use -v to see invocation)
```

```
******************** 
TEST 'Swift(macosx-arm64) :: Interop/Cxx/class/inheritance/functions.swift' FAILED
********************
Assertion failed: (wrapperModule && "CxxShim module is required when using members of a base class. " "Make sure you `import CxxShim`."), function getInteropStaticCastDeclRefExpr, file ClangImporter.cpp, line 4423.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.	Program arguments: /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend -frontend -c -primary-file /Users/mennabah/projects/os/swift-project/swift/test/Interop/Cxx/class/inheritance/functions.swift -target arm64-apple-macosx10.9 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -I /Users/mennabah/projects/os/swift-project/swift/test/Interop/Cxx/class/inheritance/Inputs/ -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -F /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/lib -module-cache-path /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/swift-test-results/arm64-apple-macosx10.9/clang-module-cache -swift-version 4 -define-availability "SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999" -define-availability "SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2" -define-availability "SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0" -define-availability "SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4" -define-availability "SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0" -define-availability "SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5" -define-availability "SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0" -define-availability "SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4" -define-availability "SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0" -define-availability "SwiftStdlib 5.8:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999" -enable-experimental-cxx-interop -target-sdk-version 12.3 -module-name main -o /var/folders/7f/4610pvjn35j3qs7cjyzzqhjc0000gn/T/lit-tmp-lcqs5pss/functions-06e159.o
1.	Swift version 5.8-dev (LLVM c87bb6a98117a76, Swift 86e633197d96169)
2.	Compiling with effective version 4.1.50
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for file "/Users/mennabah/projects/os/swift-project/swift/test/Interop/Cxx/class/inheritance/functions.swift")
4.	While silgen emitFunction SIL function "@$sSo7DerivedV11constInBaseSPys4Int8VGSgyF".
 for 'constInBase()' (in module 'Functions')
5.	While evaluating request TypeCheckFunctionBodyRequest(Functions.(file).Derived.constInBase())
6.	While evaluating request ParseAbstractFunctionBodyRequest(Functions.(file).Derived.constInBase())
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x00000001057c3a48 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x00000001057c2c3c llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x00000001057c4090 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000019b5c14c4 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000019b5a9ee0 pthread_kill + 288
5  libsystem_c.dylib        0x000000019b4e4340 abort + 168
6  libsystem_c.dylib        0x000000019b4e3754 err + 0
7  swift-frontend           0x0000000105ce6f2c getInteropStaticCastDeclRefExpr(swift::ASTContext&, clang::Module const*, swift::Type, swift::Type) (.cold.4) + 0
8  swift-frontend           0x00000001019ae8d8 getInteropStaticCastDeclRefExpr(swift::ASTContext&, clang::Module const*, swift::Type, swift::Type) + 524
9  swift-frontend           0x00000001019af8b0 synthesizeBaseClassMethodBody(swift::AbstractFunctionDecl*, void*) + 648
10 swift-frontend           0x0000000101e1efa0 swift::ParseAbstractFunctionBodyRequest::evaluate(swift::Evaluator&, swift::AbstractFunctionDecl*) const + 304
11 swift-frontend           0x0000000101c20a58 llvm::Expected<swift::ParseAbstractFunctionBodyRequest::OutputType> swift::Evaluator::getResultUncached<swift::ParseAbstractFunctionBodyRequest>(swift::ParseAbstractFunctionBodyRequest const&) + 380
12 swift-frontend           0x0000000101c2078c llvm::Expected<swift::ParseAbstractFunctionBodyRequest::OutputType> swift::Evaluator::getResultCached<swift::ParseAbstractFunctionBodyRequest, (void*)0>(swift::ParseAbstractFunctionBodyRequest const&) + 100
13 swift-frontend           0x0000000101b856d4 swift::ParseAbstractFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::ParseAbstractFunctionBodyRequest>(swift::Evaluator&, swift::ParseAbstractFunctionBodyRequest, swift::ParseAbstractFunctionBodyRequest::OutputType) + 40
14 swift-frontend           0x0000000101b6781c swift::AbstractFunctionDecl::getBody(bool) const + 196
15 swift-frontend           0x0000000101753be0 swift::TypeCheckFunctionBodyRequest::evaluate(swift::Evaluator&, swift::AbstractFunctionDecl*) const + 184
16 swift-frontend           0x0000000101c22604 llvm::Expected<swift::TypeCheckFunctionBodyRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckFunctionBodyRequest>(swift::TypeCheckFunctionBodyRequest const&) + 376
17 swift-frontend           0x0000000101c223cc llvm::Expected<swift::TypeCheckFunctionBodyRequest::OutputType> swift::Evaluator::getResultCached<swift::TypeCheckFunctionBodyRequest, (void*)0>(swift::TypeCheckFunctionBodyRequest const&) + 104
18 swift-frontend           0x0000000101b85830 swift::TypeCheckFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckFunctionBodyRequest>(swift::Evaluator&, swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType) + 36
19 swift-frontend           0x0000000100fd752c swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) + 140
20 swift-frontend           0x0000000100f63ee8 swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 6812
21 swift-frontend           0x0000000100f684a0 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 4168
22 swift-frontend           0x0000000101015908 swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> > (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 132
23 swift-frontend           0x0000000100f6badc llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::getResultUncached<swift::ASTLoweringRequest>(swift::ASTLoweringRequest const&) + 380
24 swift-frontend           0x0000000100f68784 swift::performASTLowering(swift::FileUnit&, swift::Lowering::TypeConverter&, swift::SILOptions const&, swift::IRGenOptions const*) + 80
25 swift-frontend           0x00000001009c42a0 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 520
26 swift-frontend           0x00000001009d2e6c withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
27 swift-frontend           0x00000001009c5fb0 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3248
28 swift-frontend           0x0000000100834884 swift::mainEntry(int, char const**) + 3144
29 dyld                     0x0000000118e49088 start + 516
<unknown>:0: error: unable to execute command: Abort trap: 6
<unknown>:0: error: compile command failed due to signal 6 (use -v to see invocation)
```

```
******************** 
TEST 'Swift(macosx-arm64) :: Interop/Cxx/foreign-reference/pod.swift' FAILED
********************
Assertion failed: (wrapperModule && "CxxShim module is required when using members of a base class. " "Make sure you `import CxxShim`."), function getInteropStaticCastDeclRefExpr, file ClangImporter.cpp, line 4423.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.	Program arguments: /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend -frontend -c -primary-file /Users/mennabah/projects/os/swift-project/swift/test/Interop/Cxx/foreign-reference/pod.swift -emit-module-path /var/folders/7f/4610pvjn35j3qs7cjyzzqhjc0000gn/T/lit-tmp-lcqs5pss/pod-ad6b00.swiftmodule -emit-module-doc-path /var/folders/7f/4610pvjn35j3qs7cjyzzqhjc0000gn/T/lit-tmp-lcqs5pss/pod-ad6b00.swiftdoc -emit-module-source-info-path /var/folders/7f/4610pvjn35j3qs7cjyzzqhjc0000gn/T/lit-tmp-lcqs5pss/pod-ad6b00.swiftsourceinfo -target arm64-apple-macosx10.9 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -I /Users/mennabah/projects/os/swift-project/swift/test/Interop/Cxx/foreign-reference/Inputs/ -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -F /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/lib -g -module-cache-path /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/swift-test-results/arm64-apple-macosx10.9/clang-module-cache -swift-version 4 -define-availability "SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999" -define-availability "SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2" -define-availability "SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0" -define-availability "SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4" -define-availability "SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0" -define-availability "SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5" -define-availability "SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0" -define-availability "SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4" -define-availability "SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0" -define-availability "SwiftStdlib 5.8:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999" -enable-experimental-cxx-interop -validate-tbd-against-ir=none -disable-llvm-verify -enable-anonymous-context-mangled-names -target-sdk-version 12.3 -module-name main -o /var/folders/7f/4610pvjn35j3qs7cjyzzqhjc0000gn/T/lit-tmp-lcqs5pss/pod-ad6b00.o
1.	Swift version 5.8-dev (LLVM c87bb6a98117a76, Swift 86e633197d96169)
2.	Compiling with effective version 4.1.50
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for file "/Users/mennabah/projects/os/swift-project/swift/test/Interop/Cxx/foreign-reference/pod.swift")
4.	While silgen emitFunction SIL function "@$sSo10DerivedRefV4tests5Int32VyF".
 for 'test()' (in module 'POD')
5.	While evaluating request TypeCheckFunctionBodyRequest(POD.(file).DerivedRef.test())
6.	While evaluating request ParseAbstractFunctionBodyRequest(POD.(file).DerivedRef.test())
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000109effa48 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000109efec3c llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x0000000109f00090 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000019b5c14c4 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000019b5a9ee0 pthread_kill + 288
5  libsystem_c.dylib        0x000000019b4e4340 abort + 168
6  libsystem_c.dylib        0x000000019b4e3754 err + 0
7  swift-frontend           0x000000010a422f2c getInteropStaticCastDeclRefExpr(swift::ASTContext&, clang::Module const*, swift::Type, swift::Type) (.cold.4) + 0
8  swift-frontend           0x00000001060ea8d8 getInteropStaticCastDeclRefExpr(swift::ASTContext&, clang::Module const*, swift::Type, swift::Type) + 524
9  swift-frontend           0x00000001060eb8b0 synthesizeBaseClassMethodBody(swift::AbstractFunctionDecl*, void*) + 648
10 swift-frontend           0x000000010655afa0 swift::ParseAbstractFunctionBodyRequest::evaluate(swift::Evaluator&, swift::AbstractFunctionDecl*) const + 304
11 swift-frontend           0x000000010635ca58 llvm::Expected<swift::ParseAbstractFunctionBodyRequest::OutputType> swift::Evaluator::getResultUncached<swift::ParseAbstractFunctionBodyRequest>(swift::ParseAbstractFunctionBodyRequest const&) + 380
12 swift-frontend           0x000000010635c78c llvm::Expected<swift::ParseAbstractFunctionBodyRequest::OutputType> swift::Evaluator::getResultCached<swift::ParseAbstractFunctionBodyRequest, (void*)0>(swift::ParseAbstractFunctionBodyRequest const&) + 100
13 swift-frontend           0x00000001062c16d4 swift::ParseAbstractFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::ParseAbstractFunctionBodyRequest>(swift::Evaluator&, swift::ParseAbstractFunctionBodyRequest, swift::ParseAbstractFunctionBodyRequest::OutputType) + 40
14 swift-frontend           0x00000001062a381c swift::AbstractFunctionDecl::getBody(bool) const + 196
15 swift-frontend           0x0000000105e8fbe0 swift::TypeCheckFunctionBodyRequest::evaluate(swift::Evaluator&, swift::AbstractFunctionDecl*) const + 184
16 swift-frontend           0x000000010635e604 llvm::Expected<swift::TypeCheckFunctionBodyRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckFunctionBodyRequest>(swift::TypeCheckFunctionBodyRequest const&) + 376
17 swift-frontend           0x000000010635e3cc llvm::Expected<swift::TypeCheckFunctionBodyRequest::OutputType> swift::Evaluator::getResultCached<swift::TypeCheckFunctionBodyRequest, (void*)0>(swift::TypeCheckFunctionBodyRequest const&) + 104
18 swift-frontend           0x00000001062c1830 swift::TypeCheckFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckFunctionBodyRequest>(swift::Evaluator&, swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType) + 36
19 swift-frontend           0x000000010571352c swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) + 140
20 swift-frontend           0x000000010569fee8 swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 6812
21 swift-frontend           0x00000001056a44a0 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 4168
22 swift-frontend           0x0000000105751908 swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> > (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 132
23 swift-frontend           0x00000001056a7adc llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::getResultUncached<swift::ASTLoweringRequest>(swift::ASTLoweringRequest const&) + 380
24 swift-frontend           0x00000001056a4784 swift::performASTLowering(swift::FileUnit&, swift::Lowering::TypeConverter&, swift::SILOptions const&, swift::IRGenOptions const*) + 80
25 swift-frontend           0x00000001051002a0 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 520
26 swift-frontend           0x000000010510ee6c withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
27 swift-frontend           0x0000000105101fb0 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3248
28 swift-frontend           0x0000000104f70884 swift::mainEntry(int, char const**) + 3144
29 dyld                     0x000000011d48d088 start + 516
<unknown>:0: error: unable to execute command: Abort trap: 6
<unknown>:0: error: compile command failed due to signal 6 (use -v to see invocation)
```

```
******************** 
TEST 'Swift(macosx-arm64) :: Interop/Cxx/operators/member-inline.swift' FAILED
********************
Assertion failed: (wrapperModule && "CxxShim module is required when using members of a base class. " "Make sure you `import CxxShim`."), function getInteropStaticCastDeclRefExpr, file ClangImporter.cpp, line 4423.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.	Program arguments: /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/bin/swift-frontend -frontend -c -primary-file /Users/mennabah/projects/os/swift-project/swift/test/Interop/Cxx/operators/member-inline.swift -target arm64-apple-macosx10.9 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -I /Users/mennabah/projects/os/swift-project/swift/test/Interop/Cxx/operators/Inputs -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -F /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/lib -module-cache-path /Users/mennabah/projects/os/swift-project/build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64/swift-test-results/arm64-apple-macosx10.9/clang-module-cache -swift-version 4 -define-availability "SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999" -define-availability "SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2" -define-availability "SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0" -define-availability "SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4" -define-availability "SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0" -define-availability "SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5" -define-availability "SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0" -define-availability "SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4" -define-availability "SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0" -define-availability "SwiftStdlib 5.8:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999" -enable-experimental-cxx-interop -target-sdk-version 12.3 -module-name main -o /var/folders/7f/4610pvjn35j3qs7cjyzzqhjc0000gn/T/lit-tmp-lcqs5pss/member-inline-cab5f9.o
1.	Swift version 5.8-dev (LLVM c87bb6a98117a76, Swift 86e633197d96169)
2.	Compiling with effective version 4.1.50
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for file "/Users/mennabah/projects/os/swift-project/swift/test/Interop/Cxx/operators/member-inline.swift")
4.	While silgen emitFunction SIL function "@$sSo32DerivedFromAddressOnlyIntWrapperV14callAsFunctions5Int32VyF".
 for 'callAsFunction()' (in module 'MemberInline')
5.	While evaluating request TypeCheckFunctionBodyRequest(MemberInline.(file).DerivedFromAddressOnlyIntWrapper.callAsFunction())
6.	While evaluating request ParseAbstractFunctionBodyRequest(MemberInline.(file).DerivedFromAddressOnlyIntWrapper.callAsFunction())
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x00000001094c3a48 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x00000001094c2c3c llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x00000001094c4090 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000019b5c14c4 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000019b5a9ee0 pthread_kill + 288
5  libsystem_c.dylib        0x000000019b4e4340 abort + 168
6  libsystem_c.dylib        0x000000019b4e3754 err + 0
7  swift-frontend           0x00000001099e6f2c getInteropStaticCastDeclRefExpr(swift::ASTContext&, clang::Module const*, swift::Type, swift::Type) (.cold.4) + 0
8  swift-frontend           0x00000001056ae8d8 getInteropStaticCastDeclRefExpr(swift::ASTContext&, clang::Module const*, swift::Type, swift::Type) + 524
9  swift-frontend           0x00000001056aeae0 getSelfInteropStaticCast(swift::FuncDecl*, swift::NominalTypeDecl*, swift::NominalTypeDecl*) + 488
10 swift-frontend           0x00000001056af7f0 synthesizeBaseClassMethodBody(swift::AbstractFunctionDecl*, void*) + 456
11 swift-frontend           0x0000000105b1efa0 swift::ParseAbstractFunctionBodyRequest::evaluate(swift::Evaluator&, swift::AbstractFunctionDecl*) const + 304
12 swift-frontend           0x0000000105920a58 llvm::Expected<swift::ParseAbstractFunctionBodyRequest::OutputType> swift::Evaluator::getResultUncached<swift::ParseAbstractFunctionBodyRequest>(swift::ParseAbstractFunctionBodyRequest const&) + 380
13 swift-frontend           0x000000010592078c llvm::Expected<swift::ParseAbstractFunctionBodyRequest::OutputType> swift::Evaluator::getResultCached<swift::ParseAbstractFunctionBodyRequest, (void*)0>(swift::ParseAbstractFunctionBodyRequest const&) + 100
14 swift-frontend           0x00000001058856d4 swift::ParseAbstractFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::ParseAbstractFunctionBodyRequest>(swift::Evaluator&, swift::ParseAbstractFunctionBodyRequest, swift::ParseAbstractFunctionBodyRequest::OutputType) + 40
15 swift-frontend           0x000000010586781c swift::AbstractFunctionDecl::getBody(bool) const + 196
16 swift-frontend           0x0000000105453be0 swift::TypeCheckFunctionBodyRequest::evaluate(swift::Evaluator&, swift::AbstractFunctionDecl*) const + 184
17 swift-frontend           0x0000000105922604 llvm::Expected<swift::TypeCheckFunctionBodyRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckFunctionBodyRequest>(swift::TypeCheckFunctionBodyRequest const&) + 376
18 swift-frontend           0x00000001059223cc llvm::Expected<swift::TypeCheckFunctionBodyRequest::OutputType> swift::Evaluator::getResultCached<swift::TypeCheckFunctionBodyRequest, (void*)0>(swift::TypeCheckFunctionBodyRequest const&) + 104
19 swift-frontend           0x0000000105885830 swift::TypeCheckFunctionBodyRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckFunctionBodyRequest>(swift::Evaluator&, swift::TypeCheckFunctionBodyRequest, swift::TypeCheckFunctionBodyRequest::OutputType) + 36
20 swift-frontend           0x0000000104cd752c swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) + 140
21 swift-frontend           0x0000000104c63ee8 swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 6812
22 swift-frontend           0x0000000104c684a0 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 4168
23 swift-frontend           0x0000000104d15908 swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> > (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 132
24 swift-frontend           0x0000000104c6badc llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::getResultUncached<swift::ASTLoweringRequest>(swift::ASTLoweringRequest const&) + 380
25 swift-frontend           0x0000000104c68784 swift::performASTLowering(swift::FileUnit&, swift::Lowering::TypeConverter&, swift::SILOptions const&, swift::IRGenOptions const*) + 80
26 swift-frontend           0x00000001046c42a0 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 520
27 swift-frontend           0x00000001046d2e6c withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
28 swift-frontend           0x00000001046c5fb0 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3248
29 swift-frontend           0x0000000104534884 swift::mainEntry(int, char const**) + 3144
30 dyld                     0x000000011cc4d088 start + 516
<unknown>:0: error: unable to execute command: Abort trap: 6
<unknown>:0: error: compile command failed due to signal 6 (use -v to see invocation)
```

**Comment by LucianoPAlmeida** [comment]
This is "expected" you have to re-build stdlib, go to your `build/Ninja-ReleaseWithDebugInfo/swift-macosx-arm64` folder and run `ninja swift-stdlib` after that tests should run fine.

**Comment by hamishknight** [comment]
cc @egorzhdan

**Comment by hamishknight** [comment]
This is in fact a bug, the `libcxxshim-modulemap` target is not being built by build-script, as there's a missing dependency. Manually running `ninja libcxxshim-modulemap` in the build folder for swift should work around the issue.

**Comment by egorzhdan** [comment]
cc @zoecarver
