### ISSUE TITLE
@discardableResult ignored in async context

### ISSUE THREAD

**Issue by horiz0n-zero** [apple/swift#61286]
**Describe the bug**
The attribute `@discardableResult` is ignored and produce compiler warning:
"Result of call to function returning '<My Class>' is unused"

**Steps To Reproduce**
Create a `class` 
Make this initializer `@discardableResult` ( in this case, the class maintain a memory reference to it's self )
Instantiate the class, but don't store or return the result in a `async` function/context

**Expected behavior**
The compiler should not generate warning like in a non async context.

**Screenshots**
<img width="1407" alt="Capture d’écran 2022-09-25 à 13 54 43" src="https://user-images.githubusercontent.com/20483430/192142108-13b45531-162f-4ea8-a6a7-b8cb46caaaf8.png">
<img width="1728" alt="Capture d’écran 2022-09-25 à 13 55 35" src="https://user-images.githubusercontent.com/20483430/192142147-10bb7e0e-68e2-4e26-beba-afebc7e80467.png">
<img width="1728" alt="Capture d’écran 2022-09-25 à 13 57 25" src="https://user-images.githubusercontent.com/20483430/192142224-0ea1461d-b876-4ad5-a834-da7e3f03d03b.png">

**Environment (please fill out the following information)**
 - macOS 12.6
 - Version 14.0 (14A309)
 - Swift 5.7

**Comment by xedin** [comment]
I think this is fixed by https://github.com/apple/swift/pull/60386. Please verify with the latest 5.7 branch toolchain from swift.org

**Comment by moreindirection** [comment]
I had this issue with 5.7 but can confirm the issue is fixed in the version of 5.7.1 that ships with Xcode 14.1 RC.

**Comment by simondelphia** [comment]
I am still seeing this in Xcode 14.2 in at least one spot, and I checked and I'm on Swift 5.7.2.

![image](https://user-images.githubusercontent.com/69437320/213792245-c60537da-31cf-488d-94fe-56a95a96315f.png)

my `present` function there is a custom one that is marked with `discardableResult`.

**Comment by AnthonyLatsis** [comment]
@simondelphia I think this is a different bug. Could you please open a new issue and include a self-contained test case?

**Comment by simondelphia** [comment]
Tried a few things to reproduce it in a fresh project. Thought maybe it was because of our app targeting iOS 14.3, but did that too in the new project and still no warning.
