### ISSUE TITLE
Extensions for subtype of a class marked @Observable generate compile error

### ISSUE THREAD

**Issue by virasio** [apple/swift#66450]
**Description**
I cannot add a subtype (class, enum, struct) to a class marked with `@Observable` macro. If I add an extension to this subtype, I get compile error:
> Circular reference resolving attached macro 'Observable'

**Steps to reproduce**
```swift
@Observable
class MyObservableClass {
    var property1 = ""
    var property2 = MyClass()
}

extension MyObservableClass {
    class MyClass {
        var property = ""
    }
}

extension MyObservableClass.MyClass {
    var test: String { "test \(property)" }
}
```

**Expected behavior**
It must be compilable because the following version is compilible:
```swift
@Observable
class MyObservableClass {
    var property1 = ""
    var property2 = MyClass()
}

extension MyObservableClass {
    class MyClass {
        var property = ""
        var test: String { "test \(property)" }
    }
}
```

**Environment**
Xcode 15.0 beta (15A5160n)
Swift 5.9
Target: iOS 17.0

**Comment by JessyCatterwaul** [comment]
`@Model` has the same problem. Do all macros exhibit it?

**Comment by ugoArangino** [comment]
@JessyCatterwaul Yes. It's always the same pattern.
Type`A` with a **Macro**
_extension_ type `B` nested in type `A`
_extension_ for type `B` → **compile error**

**Comment by yermukhanbet** [comment]
Are there any workarounds around this issue?

**Comment by nekno** [comment]
One workaround is to place the extension(s) in a separate file.

**Comment by juliand665** [comment]
Just ran into this as well; here's a perhaps even more minimal example:

```swift
@Observable
final class Outer {
	struct Inner {}
}

extension Outer.Inner {}
```

**Comment by mbrandonw** [comment]
+1 to this issue being a problem that definitely comes up quite a bit in every day work.

Also, regarding this:

> One workaround is to place the extension(s) in a separate file.

This can work most of the time, but sometimes it can be difficult. For example a macro applied to a generic type that needs to conditionally conform to `Equatable`:

```swift
@SomeMacro
struct Wrapper<T> { var value: T }

extension Model: Equatable where T: Equatable {}  // 🛑 Circular reference
```

If this extension is moved into a separate file then you lose the automatic synthesis of `Equatable`, and so that is unfortunate.

**Comment by li3zhen1** [comment]
Add a new case:

```swift
enum Namespace {
    @SomeMacro
    struct SomeStruct { }
}

extension Namespace.SomeStruct { }  // 🛑 Circular reference
```

**Comment by alpha-moisol** [comment]
Hello, any progress here?

**Comment by stephencelis** [comment]
We shipped a few macros this week and have had about a dozen folks report this bug to us. Would be nice to have the issue triaged.

**Comment by seungyeop-prestolabs** [comment]
It seems that this issue has been fixed in `Xcode 15.1 Beta 3`.

**Comment by DevYeom** [comment]
It seems that this issue has been fixed in `Xcode 15.1 Beta 3`.

**Comment by mbrandonw** [comment]
Hi @DevYeom, I am not able to confirm this. Both the example provided in this issue still fails to compile:

<img width="677" alt="Screenshot 2023-11-21 at 1 42 49 PM" src="https://github.com/apple/swift/assets/135203/7011a362-738d-400f-94c0-a43cb08d1676">

---

As does a simpler repro of the problem:

<img width="667" alt="image" src="https://github.com/apple/swift/assets/135203/08c0946c-9b79-4426-919e-eabec7700e1d">

---

I am using Xcode 15.1 beta 3 (15C5059c) to test this. Can anyone else confirm that it is fixed?

**Comment by DevYeom** [comment]
I'm so sorry for my misleading.

The issue I had was not related to `@Observable`, but rather with the custom member macro I created.
The message I encountered was as follows, and it was resolved in `Xcode 15.1 Beta 3`.

> Circular reference expanding member attribute macros on 'Something'

**Comment by oronbz** [comment]
With the amount of macros being utilized now by many libraries, including Apple's this problem becomes much more prominent, and also very cryptic to even understand that the harmless extension is causing it. Hope it will get addressed.

**Comment by stephencelis** [comment]
It'd be nice to at least have some acknowledgement of the problem from the core team. While we understand that there are plenty of bugs out there that need attention and triage, this one has quite a bit of activity and reach, and was opened pretty promptly the week of WWDC23.

**Comment by hborla** [comment]
A class of these circularity issues were fixed by https://github.com/apple/swift/pull/67689, which is included in Xcode 15.1 Beta 3 where some folks are seeing their specific test cases resolved. However, the `circular reference while resolving macro 'X'` errors can be manifestations of slightly different circularity paths in the type checker, which is why other people are still seeing the issue.

**Comment by crayment** [comment]
Would love to see this fixed please!!

**Comment by stephencelis** [comment]
Checked the latest snapshot this morning and sadly this is still a problem!

**Comment by acosmicflamingo** [comment]
NOOOOOOOOOOO!!!

Posting this has worked in another open-source project, so maybe it will work here! If we all collectively pray to the patron saint of computer programming, Saint Isidore of Seville, perhaps it will be addressed very soon 🙏

**Comment by IanHoar** [comment]
Also experiencing this issue

**Comment by rhysm94** [comment]
Still seeing in Xcode 15.3 and Swift 5.10, as well.

**Comment by mhelenurm** [comment]
Please give some love to this issue, Swift core team! ❤️🙏

**Comment by cmriboldi** [comment]
Yup this is a pretty bad one especially since it's a huge challenge for macros which make these extensions in the same file.

**Comment by hborla** [comment]
This is fixed in https://github.com/apple/swift/pull/71365

**Comment by vanvoorden** [comment]
@hborla Awesome! Would you know if we planned to patch this on the 5.10 branch?

**Comment by vakhidbetrakhmadov** [comment]
@hborla , thank you very much for the fix ! 
Do u happen to know what release this fix is planned to be included in ?
Would be very nice to get this fix out sooner :)

**Comment by acecilia** [comment]
Reading [here](https://www.reddit.com/r/swift/comments/1d4mahd/swift_6_is_coming/) and [here](https://forums.swift.org/t/swift-6-0-release-process/70220/7):

> confirmed that Swift 6 will be released this year, replacing the previously anticipated Swift 5.11
> ...
> Swift 6 is set to launch in 2024, alongside Xcode 16 in September, marking the first major update since Swift 5's release five years ago. This update builds on the features introduced in the Swift 5.x series, such as async/await, existentials, and macros.

So seems like the fix will be in upcoming Swift 6, in September
