### ISSUE TITLE
Compiler crash when calling a function that accepts a closure that returns a "sending" generic type 

### ISSUE THREAD

**Issue by groue** [apple/swift#74086]
### Description

The compiler crashes when calling a function that accepts a closure that returns a "sending" concrete type 

### Reproduction

Package.swift

```swift
// swift-tools-version: 5.10
import PackageDescription

let package = Package(
    name: "CompilerCrash",
    products: [
        .library(name: "CompilerCrash", targets: ["CompilerCrash"]),
    ],
    targets: [
        .target(
            name: "CompilerCrash",
            swiftSettings: [
                .enableUpcomingFeature("StrictConcurrency"),
                .enableExperimentalFeature("RegionBasedIsolation"),
                .enableExperimentalFeature("TransferringArgsAndResults"),
                .enableUpcomingFeature("InferSendableFromCaptures")
            ]
        ),
    ]
)
```

CompilerCrash.swift

```swift
func makeString() -> String { "" }
func makeVoid() { }
func intToString(_ x: Int) -> String { "" }
func intToVoid(_ x: Int) { }

func f0<Value>(_ closure: @escaping @Sendable () -> sending Value) { }
func h0String() { f0(makeString) } // <- 💣 First Compiler crash
func h0Void() { f0(makeVoid) }

func f1<Value>(_ closure: @escaping @Sendable (Int) -> sending Value) { }
func h1String() { f1(intToString) } // <- 💣 Second Compiler crash
func h1Void() { f1(intToVoid) }

func f2<Value>(_ closure: @escaping @Sendable (Int) -> Value) { }
func h2String() { f2(intToString) }
func h2Void() { f2(intToVoid) }
```

### Stack dump

```text
SwiftCompile normal arm64 Compiling\ CompilerCrash.swift /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift (in target 'CompilerCrash' from project 'CompilerCrash')
    cd /Users/groue/Desktop/CompilerCrash
    builtin-swiftTaskExecution -- /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift -emit-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.d -emit-const-values-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftconstvalues -emit-reference-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftdeps -serialize-diagnostics-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.dia -target arm64-apple-macos10.13 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -I /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-color-diagnostics -enable-testing -g -module-cache-path /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -serialize-debugging-options -package-name compilercrash -const-gather-protocols-file /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash_const_extract_protocols.json -enable-experimental-feature RegionBasedIsolation -enable-experimental-feature TransferringArgsAndResults -enable-upcoming-feature StrictConcurrency -enable-upcoming-feature InferSendableFromCaptures -empty-abi-descriptor -validate-clang-modules-once -clang-build-session-file /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/groue/Desktop/CompilerCrash -resource-dir /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/swift-overrides.hmap -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug/include -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources-normal/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG\=1 -module-name CompilerCrash -frontend-parseable-output -disable-clang-spi -target-sdk-version 14.5 -target-sdk-name macosx14.5 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/local/lib/swift/host/plugins -parse-as-library -o /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-unit-output-path /CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-store-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Index.noindex/DataStore -index-system-modules

Failed to reconstruct type for $sSiSSIeghyTo_D
Original type:
(sil_function_type type="@Sendable @callee_guaranteed (Int) -> @sil_sending @owned String"
  (input=struct_type decl="Swift.(file).Int")
  (result=struct_type decl="Swift.(file).String")
  (substitution_map null_generic_signature)
  (substitution_map null_generic_signature))
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Pass '-Xfrontend -disable-round-trip-debug-types' to disable this assertion.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift -emit-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.d -emit-const-values-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftconstvalues -emit-reference-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftdeps -serialize-diagnostics-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.dia -target arm64-apple-macos10.13 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -I /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-color-diagnostics -enable-testing -g -module-cache-path /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -serialize-debugging-options -package-name compilercrash -const-gather-protocols-file /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash_const_extract_protocols.json -enable-experimental-feature RegionBasedIsolation -enable-experimental-feature TransferringArgsAndResults -enable-upcoming-feature StrictConcurrency -enable-upcoming-feature InferSendableFromCaptures -empty-abi-descriptor -validate-clang-modules-once -clang-build-session-file /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/groue/Desktop/CompilerCrash -resource-dir /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/swift-overrides.hmap -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug/include -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources-normal/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG=1 -module-name CompilerCrash -frontend-parseable-output -disable-clang-spi -target-sdk-version 14.5 -target-sdk-name macosx14.5 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/local/lib/swift/host/plugins -parse-as-library -o /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-unit-output-path /CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-store-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Index.noindex/DataStore -index-system-modules
1.	Apple Swift version 6.0-dev (LLVM 4b0b1f9e1a69523, Swift 91a3abcf816bc36)
2.	Compiling with effective version 5.10
3.	While evaluating request IRGenRequest(IR Generation for file "/Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift")
4.	While emitting IR SIL function "@$sSiSSIeghyTo_SiSSIeghyr_TR".
 for <<debugloc at "<compiler-generated>":0:0>>Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x00000001085dbbf0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x00000001085da3bc llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x00000001085dc238 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000019c417584 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000019c3e6c20 pthread_kill + 288
5  libsystem_c.dylib        0x000000019c2f3a20 abort + 180
6  swift-frontend           0x0000000108692474 (anonymous namespace)::IRGenDebugInfoImpl::getOrCreateType(swift::irgen::DebugTypeInfo) (.cold.24) + 0
7  swift-frontend           0x000000010365a968 (anonymous namespace)::IRGenDebugInfoImpl::getOrCreateType(swift::irgen::DebugTypeInfo) + 3792
8  swift-frontend           0x000000010365adbc (anonymous namespace)::IRGenDebugInfoImpl::createParameterTypes(swift::CanTypeWrapper<swift::SILFunctionType>) + 1004
9  swift-frontend           0x000000010365367c (anonymous namespace)::IRGenDebugInfoImpl::emitFunction(swift::SILDebugScope const*, llvm::Function*, swift::SILFunctionTypeRepresentation, swift::SILType, swift::DeclContext*, llvm::StringRef) + 2124
10 swift-frontend           0x00000001036941d4 (anonymous namespace)::IRGenSILFunction::emitSILFunction() + 832
11 swift-frontend           0x0000000103693900 swift::irgen::IRGenModule::emitSILFunction(swift::SILFunction*) + 1604
12 swift-frontend           0x0000000103537b54 swift::irgen::IRGenerator::emitLazyDefinitions() + 1972
13 swift-frontend           0x00000001036460d8 swift::IRGenRequest::evaluate(swift::Evaluator&, swift::IRGenDescriptor) const + 2632
14 swift-frontend           0x0000000103692db0 swift::GeneratedModule swift::SimpleRequest<swift::IRGenRequest, swift::GeneratedModule (swift::IRGenDescriptor), (swift::RequestFlags)9>::callDerived<0ul>(swift::Evaluator&, std::__1::integer_sequence<unsigned long, 0ul>) const + 200
15 swift-frontend           0x000000010364e5c0 swift::IRGenRequest::OutputType swift::Evaluator::getResultUncached<swift::IRGenRequest, swift::IRGenRequest::OutputType swift::evaluateOrFatal<swift::IRGenRequest>(swift::Evaluator&, swift::IRGenRequest)::'lambda'()>(swift::IRGenRequest const&, swift::IRGenRequest::OutputType swift::evaluateOrFatal<swift::IRGenRequest>(swift::Evaluator&, swift::IRGenRequest)::'lambda'()) + 212
16 swift-frontend           0x0000000103647f70 swift::performIRGeneration(swift::FileUnit*, swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::StringRef, swift::PrimarySpecificPaths const&, llvm::StringRef, llvm::GlobalVariable**) + 208
17 swift-frontend           0x0000000103159824 generateIR(swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, swift::PrimarySpecificPaths const&, llvm::StringRef, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, llvm::GlobalVariable*&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>) + 156
18 swift-frontend           0x0000000103155ac4 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 1416
19 swift-frontend           0x0000000103154f2c swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 648
20 swift-frontend           0x0000000103166248 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
21 swift-frontend           0x0000000103157590 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 708
22 swift-frontend           0x00000001031564fc swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2388
23 swift-frontend           0x0000000102f703b0 swift::mainEntry(int, char const**) + 3096
24 dyld                     0x000000019c05e0e0 start + 2360
Command SwiftCompile failed with a nonzero exit code
```

### Expected behavior

No compiler crash

### Environment

```
% /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/bin/swiftc -version
Apple Swift version 6.0-dev (LLVM 4b0b1f9e1a69523, Swift 91a3abcf816bc36)
Target: arm64-apple-macosx14.0
```

### Additional information

Probably related to #74085

**Comment by gottesmm** [comment]
@groue I just tried with swift-DEVELOPMENT-SNAPSHOT-2024-06-05-a and I am not reproducing. Can you verify on your side? I believe this was fixed by: https://github.com/apple/swift/commit/f45a87cf2cdaa57da9b5cac05e6e1b4a0a0b35ec

**Comment by groue** [comment]
Hello @gottesmm, the code above still crashes:

<details><summary>swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a</summary>

```
SwiftCompile normal arm64 Compiling\ CompilerCrash.swift /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift (in target 'CompilerCrash' from project 'CompilerCrash')
    cd /Users/groue/Desktop/CompilerCrash
    builtin-swiftTaskExecution -- /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift -emit-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.d -emit-const-values-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftconstvalues -emit-reference-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftdeps -serialize-diagnostics-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.dia -target arm64-apple-macos10.13 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -I /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-color-diagnostics -enable-testing -g -module-cache-path /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -serialize-debugging-options -package-name compilercrash -const-gather-protocols-file /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash_const_extract_protocols.json -enable-experimental-feature RegionBasedIsolation -enable-experimental-feature TransferringArgsAndResults -enable-upcoming-feature StrictConcurrency -enable-upcoming-feature InferSendableFromCaptures -empty-abi-descriptor -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift/host/plugins -validate-clang-modules-once -clang-build-session-file /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/groue/Desktop/CompilerCrash -resource-dir /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/swift-overrides.hmap -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug/include -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources-normal/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG\=1 -module-name CompilerCrash -frontend-parseable-output -disable-clang-spi -target-sdk-version 14.5 -target-sdk-name macosx14.5 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/local/lib/swift/host/plugins -parse-as-library -o /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-unit-output-path /CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-store-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Index.noindex/DataStore -index-system-modules

Failed to reconstruct type for $sSSIeghTo_D
Original type:
(sil_function_type type="@Sendable @callee_guaranteed () -> @sil_sending @owned String"
  (result=struct_type decl="Swift.(file).String")
  (substitution_map null_generic_signature)
  (substitution_map null_generic_signature))
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Pass '-Xfrontend -disable-round-trip-debug-types' to disable this assertion.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift -emit-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.d -emit-const-values-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftconstvalues -emit-reference-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftdeps -serialize-diagnostics-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.dia -target arm64-apple-macos10.13 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -I /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-color-diagnostics -enable-testing -g -module-cache-path /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -serialize-debugging-options -package-name compilercrash -const-gather-protocols-file /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash_const_extract_protocols.json -enable-experimental-feature RegionBasedIsolation -enable-experimental-feature TransferringArgsAndResults -enable-upcoming-feature StrictConcurrency -enable-upcoming-feature InferSendableFromCaptures -empty-abi-descriptor -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift/host/plugins -validate-clang-modules-once -clang-build-session-file /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/groue/Desktop/CompilerCrash -resource-dir /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/swift-overrides.hmap -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug/include -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources-normal/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG=1 -module-name CompilerCrash -frontend-parseable-output -disable-clang-spi -target-sdk-version 14.5 -target-sdk-name macosx14.5 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/local/lib/swift/host/plugins -parse-as-library -o /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-unit-output-path /CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-store-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Index.noindex/DataStore -index-system-modules
1.	Apple Swift version 6.0-dev (LLVM 25f401da89fc02a, Swift dbe1a982d9252c9)
2.	Compiling with effective version 5.10
3.	While evaluating request IRGenRequest(IR Generation for file "/Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift")
4.	While emitting IR SIL function "@$sSSIeghTo_SSIeghr_TR".
 for <<debugloc at "<compiler-generated>":0:0>>Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000105b16138 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000105b14904 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x0000000105b16780 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000019c417584 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000019c3e6c20 pthread_kill + 288
5  libsystem_c.dylib        0x000000019c2f3a20 abort + 180
6  swift-frontend           0x0000000105bcf250 (anonymous namespace)::IRGenDebugInfoImpl::getOrCreateType(swift::irgen::DebugTypeInfo) (.cold.24) + 0
7  swift-frontend           0x0000000100b6dbe4 (anonymous namespace)::IRGenDebugInfoImpl::getOrCreateType(swift::irgen::DebugTypeInfo) + 3792
8  swift-frontend           0x0000000100b6e00c (anonymous namespace)::IRGenDebugInfoImpl::createParameterTypes(swift::CanTypeWrapper<swift::SILFunctionType>) + 960
9  swift-frontend           0x0000000100b668bc (anonymous namespace)::IRGenDebugInfoImpl::emitFunction(swift::SILDebugScope const*, llvm::Function*, swift::SILFunctionTypeRepresentation, swift::SILType, swift::DeclContext*, llvm::StringRef) + 2120
10 swift-frontend           0x0000000100ba7eb0 (anonymous namespace)::IRGenSILFunction::emitSILFunction() + 828
11 swift-frontend           0x0000000100ba75e0 swift::irgen::IRGenModule::emitSILFunction(swift::SILFunction*) + 1528
12 swift-frontend           0x0000000100a473c0 swift::irgen::IRGenerator::emitLazyDefinitions() + 1972
13 swift-frontend           0x0000000100b5901c swift::IRGenRequest::evaluate(swift::Evaluator&, swift::IRGenDescriptor) const + 2636
14 swift-frontend           0x0000000100ba6adc swift::GeneratedModule swift::SimpleRequest<swift::IRGenRequest, swift::GeneratedModule (swift::IRGenDescriptor), (swift::RequestFlags)9>::callDerived<0ul>(swift::Evaluator&, std::__1::integer_sequence<unsigned long, 0ul>) const + 200
15 swift-frontend           0x0000000100b61788 swift::IRGenRequest::OutputType swift::Evaluator::getResultUncached<swift::IRGenRequest, swift::IRGenRequest::OutputType swift::evaluateOrFatal<swift::IRGenRequest>(swift::Evaluator&, swift::IRGenRequest)::'lambda'()>(swift::IRGenRequest const&, swift::IRGenRequest::OutputType swift::evaluateOrFatal<swift::IRGenRequest>(swift::Evaluator&, swift::IRGenRequest)::'lambda'()) + 212
16 swift-frontend           0x0000000100b5aeb4 swift::performIRGeneration(swift::FileUnit*, swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::StringRef, swift::PrimarySpecificPaths const&, llvm::StringRef, llvm::GlobalVariable**) + 208
17 swift-frontend           0x0000000100663d54 generateIR(swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, swift::PrimarySpecificPaths const&, llvm::StringRef, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, llvm::GlobalVariable*&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>) + 156
18 swift-frontend           0x000000010065fff4 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 1416
19 swift-frontend           0x000000010065f44c swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 656
20 swift-frontend           0x00000001006707f4 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
21 swift-frontend           0x0000000100661ab4 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 708
22 swift-frontend           0x0000000100660a20 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2376
23 swift-frontend           0x000000010046b040 swift::mainEntry(int, char const**) + 3096
24 dyld                     0x000000019c05e0e0 start + 2360
Command SwiftCompile failed with a nonzero exit code
```

</details>

<details><summary>swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a</summary>

```
SwiftCompile normal arm64 Compiling\ CompilerCrash.swift /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift (in target 'CompilerCrash' from project 'CompilerCrash')
    cd /Users/groue/Desktop/CompilerCrash
    builtin-swiftTaskExecution -- /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift -emit-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.d -emit-const-values-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftconstvalues -emit-reference-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftdeps -serialize-diagnostics-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.dia -target arm64-apple-macos10.13 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -I /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-color-diagnostics -enable-testing -g -module-cache-path /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -serialize-debugging-options -package-name compilercrash -const-gather-protocols-file /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash_const_extract_protocols.json -enable-experimental-feature RegionBasedIsolation -enable-experimental-feature TransferringArgsAndResults -enable-upcoming-feature StrictConcurrency -enable-upcoming-feature InferSendableFromCaptures -empty-abi-descriptor -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift/host/plugins -validate-clang-modules-once -clang-build-session-file /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/groue/Desktop/CompilerCrash -resource-dir /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/swift-overrides.hmap -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug/include -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources-normal/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG\=1 -module-name CompilerCrash -frontend-parseable-output -disable-clang-spi -target-sdk-version 14.5 -target-sdk-name macosx14.5 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/local/lib/swift/host/plugins -parse-as-library -o /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-unit-output-path /CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-store-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Index.noindex/DataStore -index-system-modules

Failed to reconstruct type for $sSSIeghTo_D
Original type:
(sil_function_type type="@Sendable @callee_guaranteed () -> @sil_sending @owned String"
  (result=struct_type decl="Swift.(file).String")
  (substitution_map null_generic_signature)
  (substitution_map null_generic_signature))
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Pass '-Xfrontend -disable-round-trip-debug-types' to disable this assertion.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift -emit-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.d -emit-const-values-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftconstvalues -emit-reference-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftdeps -serialize-diagnostics-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.dia -target arm64-apple-macos10.13 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -I /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-color-diagnostics -enable-testing -g -module-cache-path /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -serialize-debugging-options -package-name compilercrash -const-gather-protocols-file /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash_const_extract_protocols.json -enable-experimental-feature RegionBasedIsolation -enable-experimental-feature TransferringArgsAndResults -enable-upcoming-feature StrictConcurrency -enable-upcoming-feature InferSendableFromCaptures -empty-abi-descriptor -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift/host/plugins -validate-clang-modules-once -clang-build-session-file /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/groue/Desktop/CompilerCrash -resource-dir /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/swift-overrides.hmap -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug/include -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources-normal/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG=1 -module-name CompilerCrash -frontend-parseable-output -disable-clang-spi -target-sdk-version 14.5 -target-sdk-name macosx14.5 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/local/lib/swift/host/plugins -parse-as-library -o /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-unit-output-path /CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-store-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Index.noindex/DataStore -index-system-modules
1.	Apple Swift version 6.0-dev (LLVM bf8bbb910874156, Swift 2a6163f0e50d955)
2.	Compiling with effective version 5.10
3.	While evaluating request IRGenRequest(IR Generation for file "/Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift")
4.	While emitting IR SIL function "@$sSSIeghTo_SSIeghr_TR".
 for <<debugloc at "<compiler-generated>":0:0>>Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000109737274 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000109735a40 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x00000001097378bc SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000019c417584 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000019c3e6c20 pthread_kill + 288
5  libsystem_c.dylib        0x000000019c2f3a20 abort + 180
6  swift-frontend           0x00000001097edc80 (anonymous namespace)::IRGenDebugInfoImpl::getOrCreateType(swift::irgen::DebugTypeInfo) (.cold.24) + 0
7  swift-frontend           0x00000001047a83dc (anonymous namespace)::IRGenDebugInfoImpl::getOrCreateType(swift::irgen::DebugTypeInfo) + 3792
8  swift-frontend           0x00000001047a8830 (anonymous namespace)::IRGenDebugInfoImpl::createParameterTypes(swift::CanTypeWrapper<swift::SILFunctionType>) + 1004
9  swift-frontend           0x00000001047a10f0 (anonymous namespace)::IRGenDebugInfoImpl::emitFunction(swift::SILDebugScope const*, llvm::Function*, swift::SILFunctionTypeRepresentation, swift::SILType, swift::DeclContext*, llvm::StringRef) + 2124
10 swift-frontend           0x00000001047e1c5c (anonymous namespace)::IRGenSILFunction::emitSILFunction() + 832
11 swift-frontend           0x00000001047e1388 swift::irgen::IRGenModule::emitSILFunction(swift::SILFunction*) + 1604
12 swift-frontend           0x0000000104685638 swift::irgen::IRGenerator::emitLazyDefinitions() + 1972
13 swift-frontend           0x0000000104793b4c swift::IRGenRequest::evaluate(swift::Evaluator&, swift::IRGenDescriptor) const + 2632
14 swift-frontend           0x00000001047e0838 swift::GeneratedModule swift::SimpleRequest<swift::IRGenRequest, swift::GeneratedModule (swift::IRGenDescriptor), (swift::RequestFlags)9>::callDerived<0ul>(swift::Evaluator&, std::__1::integer_sequence<unsigned long, 0ul>) const + 200
15 swift-frontend           0x000000010479c034 swift::IRGenRequest::OutputType swift::Evaluator::getResultUncached<swift::IRGenRequest, swift::IRGenRequest::OutputType swift::evaluateOrFatal<swift::IRGenRequest>(swift::Evaluator&, swift::IRGenRequest)::'lambda'()>(swift::IRGenRequest const&, swift::IRGenRequest::OutputType swift::evaluateOrFatal<swift::IRGenRequest>(swift::Evaluator&, swift::IRGenRequest)::'lambda'()) + 212
16 swift-frontend           0x00000001047959e4 swift::performIRGeneration(swift::FileUnit*, swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::StringRef, swift::PrimarySpecificPaths const&, llvm::StringRef, llvm::GlobalVariable**) + 208
17 swift-frontend           0x00000001042a5f58 generateIR(swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, swift::PrimarySpecificPaths const&, llvm::StringRef, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, llvm::GlobalVariable*&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>) + 156
18 swift-frontend           0x00000001042a2204 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 1416
19 swift-frontend           0x00000001042a1664 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 656
20 swift-frontend           0x00000001042b298c withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
21 swift-frontend           0x00000001042a3cc4 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 708
22 swift-frontend           0x00000001042a2c30 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2376
23 swift-frontend           0x00000001040bcc2c swift::mainEntry(int, char const**) + 3096
24 dyld                     0x000000019c05e0e0 start + 2360
Command SwiftCompile failed with a nonzero exit code
```

</details>

**Comment by groue** [comment]
Fixed in Xcode 16.0 beta (16A5171c).
