### ISSUE TITLE
Crash when defining a method that accepts a closure that returns a "sending" concrete type

### ISSUE THREAD

**Issue by groue** [apple/swift#74085]
### Description

The compiler crashes when it compiles a function that accepts an closure that returns a sendable concrete type.

### Reproduction

CompilerCrash/Package.swift:

```swift
// swift-tools-version: 5.10
import PackageDescription

let package = Package(
    name: "CompilerCrash",
    products: [
        .library(name: "CompilerCrash", targets: ["CompilerCrash"]),
    ],
    targets: [
        .target(
            name: "CompilerCrash",
            swiftSettings: [
                .enableUpcomingFeature("StrictConcurrency"),
                .enableExperimentalFeature("RegionBasedIsolation"),
                .enableExperimentalFeature("TransferringArgsAndResults"),
                .enableUpcomingFeature("InferSendableFromCaptures")
            ]
        ),
    ]
)
```

CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift:

```swift
// Each one of those functions crashes the compiler.
func f1(_ closure: @escaping @Sendable () -> sending Int) { }
func f2(_ closure: @Sendable () -> sending Int) { }
func f3(_ closure: @escaping () -> sending Int) { }
func f4(_ closure: () -> sending Int) { }

// No compiler crash
func ok1<Value>(_ closure: @escaping @Sendable () -> Value) { }
func ok2<Value>(_ closure: @escaping @Sendable () -> sending Value) { }
```

### Stack dump

```text
SwiftCompile normal arm64 Compiling\ CompilerCrash.swift /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift (in target 'CompilerCrash' from project 'CompilerCrash')
    cd /Users/groue/Desktop/CompilerCrash
    builtin-swiftTaskExecution -- /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift -emit-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.d -emit-const-values-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftconstvalues -emit-reference-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftdeps -serialize-diagnostics-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.dia -target arm64-apple-macos10.13 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -I /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-color-diagnostics -enable-testing -g -module-cache-path /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -serialize-debugging-options -package-name compilercrash -const-gather-protocols-file /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash_const_extract_protocols.json -enable-experimental-feature RegionBasedIsolation -enable-experimental-feature TransferringArgsAndResults -enable-upcoming-feature StrictConcurrency -enable-upcoming-feature InferSendableFromCaptures -empty-abi-descriptor -validate-clang-modules-once -clang-build-session-file /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/groue/Desktop/CompilerCrash -resource-dir /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/swift-overrides.hmap -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug/include -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources-normal/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG\=1 -module-name CompilerCrash -frontend-parseable-output -disable-clang-spi -target-sdk-version 14.5 -target-sdk-name macosx14.5 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/local/lib/swift/host/plugins -parse-as-library -o /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-unit-output-path /CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-store-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Index.noindex/DataStore -index-system-modules

Failed to reconstruct type for $sSiIeghTd_D
Original type:
(sil_function_type type="@Sendable @callee_guaranteed () -> @sil_sending Int"
  (result=struct_type decl="Swift.(file).Int")
  (substitution_map null_generic_signature)
  (substitution_map null_generic_signature))
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Pass '-Xfrontend -disable-round-trip-debug-types' to disable this assertion.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift -emit-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.d -emit-const-values-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftconstvalues -emit-reference-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftdeps -serialize-diagnostics-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.dia -target arm64-apple-macos10.13 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -I /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-color-diagnostics -enable-testing -g -module-cache-path /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -serialize-debugging-options -package-name compilercrash -const-gather-protocols-file /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash_const_extract_protocols.json -enable-experimental-feature RegionBasedIsolation -enable-experimental-feature TransferringArgsAndResults -enable-upcoming-feature StrictConcurrency -enable-upcoming-feature InferSendableFromCaptures -empty-abi-descriptor -validate-clang-modules-once -clang-build-session-file /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/groue/Desktop/CompilerCrash -resource-dir /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/swift-overrides.hmap -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug/include -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources-normal/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG=1 -module-name CompilerCrash -frontend-parseable-output -disable-clang-spi -target-sdk-version 14.5 -target-sdk-name macosx14.5 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/local/lib/swift/host/plugins -parse-as-library -o /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-unit-output-path /CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-store-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Index.noindex/DataStore -index-system-modules
1.	Apple Swift version 6.0-dev (LLVM 4b0b1f9e1a69523, Swift 91a3abcf816bc36)
2.	Compiling with effective version 5.10
3.	While evaluating request IRGenRequest(IR Generation for file "/Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift")
4.	While emitting IR SIL function "@$s13CompilerCrash2f1yySiyYbYTcF".
 for 'f1(_:)' (at /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift:1:1)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000010a617bf0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x000000010a6163bc llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x000000010a618238 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000019c417584 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000019c3e6c20 pthread_kill + 288
5  libsystem_c.dylib        0x000000019c2f3a20 abort + 180
6  swift-frontend           0x000000010a6ce474 (anonymous namespace)::IRGenDebugInfoImpl::getOrCreateType(swift::irgen::DebugTypeInfo) (.cold.24) + 0
7  swift-frontend           0x0000000105696968 (anonymous namespace)::IRGenDebugInfoImpl::getOrCreateType(swift::irgen::DebugTypeInfo) + 3792
8  swift-frontend           0x0000000105696dbc (anonymous namespace)::IRGenDebugInfoImpl::createParameterTypes(swift::CanTypeWrapper<swift::SILFunctionType>) + 1004
9  swift-frontend           0x000000010568f67c (anonymous namespace)::IRGenDebugInfoImpl::emitFunction(swift::SILDebugScope const*, llvm::Function*, swift::SILFunctionTypeRepresentation, swift::SILType, swift::DeclContext*, llvm::StringRef) + 2124
10 swift-frontend           0x00000001056d01d4 (anonymous namespace)::IRGenSILFunction::emitSILFunction() + 832
11 swift-frontend           0x00000001056cf900 swift::irgen::IRGenModule::emitSILFunction(swift::SILFunction*) + 1604
12 swift-frontend           0x00000001055723e8 swift::irgen::IRGenerator::emitGlobalTopLevel(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) + 740
13 swift-frontend           0x0000000105681f0c swift::IRGenRequest::evaluate(swift::Evaluator&, swift::IRGenDescriptor) const + 2172
14 swift-frontend           0x00000001056cedb0 swift::GeneratedModule swift::SimpleRequest<swift::IRGenRequest, swift::GeneratedModule (swift::IRGenDescriptor), (swift::RequestFlags)9>::callDerived<0ul>(swift::Evaluator&, std::__1::integer_sequence<unsigned long, 0ul>) const + 200
15 swift-frontend           0x000000010568a5c0 swift::IRGenRequest::OutputType swift::Evaluator::getResultUncached<swift::IRGenRequest, swift::IRGenRequest::OutputType swift::evaluateOrFatal<swift::IRGenRequest>(swift::Evaluator&, swift::IRGenRequest)::'lambda'()>(swift::IRGenRequest const&, swift::IRGenRequest::OutputType swift::evaluateOrFatal<swift::IRGenRequest>(swift::Evaluator&, swift::IRGenRequest)::'lambda'()) + 212
16 swift-frontend           0x0000000105683f70 swift::performIRGeneration(swift::FileUnit*, swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::StringRef, swift::PrimarySpecificPaths const&, llvm::StringRef, llvm::GlobalVariable**) + 208
17 swift-frontend           0x0000000105195824 generateIR(swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, swift::PrimarySpecificPaths const&, llvm::StringRef, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, llvm::GlobalVariable*&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>) + 156
18 swift-frontend           0x0000000105191ac4 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 1416
19 swift-frontend           0x0000000105190f2c swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 648
20 swift-frontend           0x00000001051a2248 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
21 swift-frontend           0x0000000105193590 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 708
22 swift-frontend           0x00000001051924fc swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2388
23 swift-frontend           0x0000000104fac3b0 swift::mainEntry(int, char const**) + 3096
24 dyld                     0x000000019c05e0e0 start + 2360
Command SwiftCompile failed with a nonzero exit code
```

### Expected behavior

No crash

### Environment

```
% /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-05-26-a.xctoolchain/usr/bin/swiftc -version
Apple Swift version 6.0-dev (LLVM 4b0b1f9e1a69523, Swift 91a3abcf816bc36)
Target: arm64-apple-macosx14.0
```

### Additional information

Probably related to #74086

**Comment by xedin** [comment]
@gottesmm could you please take a look at this one? I saw a few PRs about mangling and `sending` maybe they’ll address this issue as well…

**Comment by gottesmm** [comment]
I think I already fixed this here: f45a87cf2cdaa57da9b5cac05e6e1b4a0a0b35ec

**Comment by gottesmm** [comment]
@groue I just tried with swift-DEVELOPMENT-SNAPSHOT-2024-06-05-a and I am not reproducing. Can you verify on your side?

**Comment by groue** [comment]
Hello @gottesmm,

The above code still crashes:

<details><summary>swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a</summary>

```
SwiftCompile normal arm64 Compiling\ CompilerCrash.swift /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift (in target 'CompilerCrash' from project 'CompilerCrash')
    cd /Users/groue/Desktop/CompilerCrash
    builtin-swiftTaskExecution -- /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift -emit-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.d -emit-const-values-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftconstvalues -emit-reference-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftdeps -serialize-diagnostics-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.dia -target arm64-apple-macos10.13 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -I /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-color-diagnostics -enable-testing -g -module-cache-path /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -serialize-debugging-options -package-name compilercrash -const-gather-protocols-file /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash_const_extract_protocols.json -enable-experimental-feature RegionBasedIsolation -enable-experimental-feature TransferringArgsAndResults -enable-upcoming-feature StrictConcurrency -enable-upcoming-feature InferSendableFromCaptures -empty-abi-descriptor -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift/host/plugins -validate-clang-modules-once -clang-build-session-file /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/groue/Desktop/CompilerCrash -resource-dir /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/swift-overrides.hmap -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug/include -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources-normal/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG\=1 -module-name CompilerCrash -frontend-parseable-output -disable-clang-spi -target-sdk-version 14.5 -target-sdk-name macosx14.5 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/local/lib/swift/host/plugins -parse-as-library -o /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-unit-output-path /CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-store-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Index.noindex/DataStore -index-system-modules

Failed to reconstruct type for $sSiIeghTd_D
Original type:
(sil_function_type type="@Sendable @callee_guaranteed () -> @sil_sending Int"
  (result=struct_type decl="Swift.(file).Int")
  (substitution_map null_generic_signature)
  (substitution_map null_generic_signature))
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Pass '-Xfrontend -disable-round-trip-debug-types' to disable this assertion.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift -emit-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.d -emit-const-values-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftconstvalues -emit-reference-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftdeps -serialize-diagnostics-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.dia -target arm64-apple-macos10.13 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -I /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-color-diagnostics -enable-testing -g -module-cache-path /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -serialize-debugging-options -package-name compilercrash -const-gather-protocols-file /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash_const_extract_protocols.json -enable-experimental-feature RegionBasedIsolation -enable-experimental-feature TransferringArgsAndResults -enable-upcoming-feature StrictConcurrency -enable-upcoming-feature InferSendableFromCaptures -empty-abi-descriptor -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift/host/plugins -validate-clang-modules-once -clang-build-session-file /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/groue/Desktop/CompilerCrash -resource-dir /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/swift-overrides.hmap -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug/include -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources-normal/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG=1 -module-name CompilerCrash -frontend-parseable-output -disable-clang-spi -target-sdk-version 14.5 -target-sdk-name macosx14.5 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/local/lib/swift/host/plugins -parse-as-library -o /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-unit-output-path /CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-store-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Index.noindex/DataStore -index-system-modules
1.	Apple Swift version 6.0-dev (LLVM 25f401da89fc02a, Swift dbe1a982d9252c9)
2.	Compiling with effective version 5.10
3.	While evaluating request IRGenRequest(IR Generation for file "/Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift")
4.	While emitting IR SIL function "@$s13CompilerCrash2f1yySiyYbYTcF".
 for 'f1(_:)' (at /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift:2:1)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000107cb2138 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000107cb0904 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x0000000107cb2780 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000019c417584 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000019c3e6c20 pthread_kill + 288
5  libsystem_c.dylib        0x000000019c2f3a20 abort + 180
6  swift-frontend           0x0000000107d6b250 (anonymous namespace)::IRGenDebugInfoImpl::getOrCreateType(swift::irgen::DebugTypeInfo) (.cold.24) + 0
7  swift-frontend           0x0000000102d09be4 (anonymous namespace)::IRGenDebugInfoImpl::getOrCreateType(swift::irgen::DebugTypeInfo) + 3792
8  swift-frontend           0x0000000102d0a00c (anonymous namespace)::IRGenDebugInfoImpl::createParameterTypes(swift::CanTypeWrapper<swift::SILFunctionType>) + 960
9  swift-frontend           0x0000000102d028bc (anonymous namespace)::IRGenDebugInfoImpl::emitFunction(swift::SILDebugScope const*, llvm::Function*, swift::SILFunctionTypeRepresentation, swift::SILType, swift::DeclContext*, llvm::StringRef) + 2120
10 swift-frontend           0x0000000102d43eb0 (anonymous namespace)::IRGenSILFunction::emitSILFunction() + 828
11 swift-frontend           0x0000000102d435e0 swift::irgen::IRGenModule::emitSILFunction(swift::SILFunction*) + 1528
12 swift-frontend           0x0000000102be1c7c swift::irgen::IRGenerator::emitGlobalTopLevel(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) + 752
13 swift-frontend           0x0000000102cf4e4c swift::IRGenRequest::evaluate(swift::Evaluator&, swift::IRGenDescriptor) const + 2172
14 swift-frontend           0x0000000102d42adc swift::GeneratedModule swift::SimpleRequest<swift::IRGenRequest, swift::GeneratedModule (swift::IRGenDescriptor), (swift::RequestFlags)9>::callDerived<0ul>(swift::Evaluator&, std::__1::integer_sequence<unsigned long, 0ul>) const + 200
15 swift-frontend           0x0000000102cfd788 swift::IRGenRequest::OutputType swift::Evaluator::getResultUncached<swift::IRGenRequest, swift::IRGenRequest::OutputType swift::evaluateOrFatal<swift::IRGenRequest>(swift::Evaluator&, swift::IRGenRequest)::'lambda'()>(swift::IRGenRequest const&, swift::IRGenRequest::OutputType swift::evaluateOrFatal<swift::IRGenRequest>(swift::Evaluator&, swift::IRGenRequest)::'lambda'()) + 212
16 swift-frontend           0x0000000102cf6eb4 swift::performIRGeneration(swift::FileUnit*, swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::StringRef, swift::PrimarySpecificPaths const&, llvm::StringRef, llvm::GlobalVariable**) + 208
17 swift-frontend           0x00000001027ffd54 generateIR(swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, swift::PrimarySpecificPaths const&, llvm::StringRef, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, llvm::GlobalVariable*&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>) + 156
18 swift-frontend           0x00000001027fbff4 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 1416
19 swift-frontend           0x00000001027fb44c swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 656
20 swift-frontend           0x000000010280c7f4 withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
21 swift-frontend           0x00000001027fdab4 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 708
22 swift-frontend           0x00000001027fca20 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2376
23 swift-frontend           0x0000000102607040 swift::mainEntry(int, char const**) + 3096
24 dyld                     0x000000019c05e0e0 start + 2360
Command SwiftCompile failed with a nonzero exit code
```

</details>

<details><summary>swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a</summary>

```
SwiftCompile normal arm64 Compiling\ CompilerCrash.swift /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift (in target 'CompilerCrash' from project 'CompilerCrash')
    cd /Users/groue/Desktop/CompilerCrash
    builtin-swiftTaskExecution -- /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift -emit-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.d -emit-const-values-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftconstvalues -emit-reference-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftdeps -serialize-diagnostics-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.dia -target arm64-apple-macos10.13 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -I /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-color-diagnostics -enable-testing -g -module-cache-path /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -serialize-debugging-options -package-name compilercrash -const-gather-protocols-file /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash_const_extract_protocols.json -enable-experimental-feature RegionBasedIsolation -enable-experimental-feature TransferringArgsAndResults -enable-upcoming-feature StrictConcurrency -enable-upcoming-feature InferSendableFromCaptures -empty-abi-descriptor -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift/host/plugins -validate-clang-modules-once -clang-build-session-file /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/groue/Desktop/CompilerCrash -resource-dir /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/swift-overrides.hmap -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug/include -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources-normal/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG\=1 -module-name CompilerCrash -frontend-parseable-output -disable-clang-spi -target-sdk-version 14.5 -target-sdk-name macosx14.5 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins\#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/local/lib/swift/host/plugins -parse-as-library -o /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-unit-output-path /CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-store-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Index.noindex/DataStore -index-system-modules

Failed to reconstruct type for $sSiIeghTd_D
Original type:
(sil_function_type type="@Sendable @callee_guaranteed () -> @sil_sending Int"
  (result=struct_type decl="Swift.(file).Int")
  (substitution_map null_generic_signature)
  (substitution_map null_generic_signature))
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Pass '-Xfrontend -disable-round-trip-debug-types' to disable this assertion.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift -emit-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.d -emit-const-values-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftconstvalues -emit-reference-dependencies-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.swiftdeps -serialize-diagnostics-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.dia -target arm64-apple-macos10.13 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -I /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-color-diagnostics -enable-testing -g -module-cache-path /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -serialize-debugging-options -package-name compilercrash -const-gather-protocols-file /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash_const_extract_protocols.json -enable-experimental-feature RegionBasedIsolation -enable-experimental-feature TransferringArgsAndResults -enable-upcoming-feature StrictConcurrency -enable-upcoming-feature InferSendableFromCaptures -empty-abi-descriptor -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift/host/plugins -validate-clang-modules-once -clang-build-session-file /Users/groue/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -Xcc -working-directory -Xcc /Users/groue/Desktop/CompilerCrash -resource-dir /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/swift-overrides.hmap -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Products/Debug/include -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources-normal/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources/arm64 -Xcc -I/Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG=1 -module-name CompilerCrash -frontend-parseable-output -disable-clang-spi -target-sdk-version 14.5 -target-sdk-name macosx14.5 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-07-a.xctoolchain/usr/local/lib/swift/host/plugins -parse-as-library -o /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Build/Intermediates.noindex/CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-unit-output-path /CompilerCrash.build/Debug/CompilerCrash.build/Objects-normal/arm64/CompilerCrash.o -index-store-path /Users/groue/Library/Developer/Xcode/DerivedData/CompilerCrash-grvxvnexlbydsvbdglqyzzvdyhpc/Index.noindex/DataStore -index-system-modules
1.	Apple Swift version 6.0-dev (LLVM bf8bbb910874156, Swift 2a6163f0e50d955)
2.	Compiling with effective version 5.10
3.	While evaluating request IRGenRequest(IR Generation for file "/Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift")
4.	While emitting IR SIL function "@$s13CompilerCrash2f1yySiyYbYTcF".
 for 'f1(_:)' (at /Users/groue/Desktop/CompilerCrash/Sources/CompilerCrash/CompilerCrash.swift:2:1)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000010a15b274 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x000000010a159a40 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x000000010a15b8bc SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000019c417584 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000019c3e6c20 pthread_kill + 288
5  libsystem_c.dylib        0x000000019c2f3a20 abort + 180
6  swift-frontend           0x000000010a211c80 (anonymous namespace)::IRGenDebugInfoImpl::getOrCreateType(swift::irgen::DebugTypeInfo) (.cold.24) + 0
7  swift-frontend           0x00000001051cc3dc (anonymous namespace)::IRGenDebugInfoImpl::getOrCreateType(swift::irgen::DebugTypeInfo) + 3792
8  swift-frontend           0x00000001051cc830 (anonymous namespace)::IRGenDebugInfoImpl::createParameterTypes(swift::CanTypeWrapper<swift::SILFunctionType>) + 1004
9  swift-frontend           0x00000001051c50f0 (anonymous namespace)::IRGenDebugInfoImpl::emitFunction(swift::SILDebugScope const*, llvm::Function*, swift::SILFunctionTypeRepresentation, swift::SILType, swift::DeclContext*, llvm::StringRef) + 2124
10 swift-frontend           0x0000000105205c5c (anonymous namespace)::IRGenSILFunction::emitSILFunction() + 832
11 swift-frontend           0x0000000105205388 swift::irgen::IRGenModule::emitSILFunction(swift::SILFunction*) + 1604
12 swift-frontend           0x00000001050a7ecc swift::irgen::IRGenerator::emitGlobalTopLevel(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) + 740
13 swift-frontend           0x00000001051b7980 swift::IRGenRequest::evaluate(swift::Evaluator&, swift::IRGenDescriptor) const + 2172
14 swift-frontend           0x0000000105204838 swift::GeneratedModule swift::SimpleRequest<swift::IRGenRequest, swift::GeneratedModule (swift::IRGenDescriptor), (swift::RequestFlags)9>::callDerived<0ul>(swift::Evaluator&, std::__1::integer_sequence<unsigned long, 0ul>) const + 200
15 swift-frontend           0x00000001051c0034 swift::IRGenRequest::OutputType swift::Evaluator::getResultUncached<swift::IRGenRequest, swift::IRGenRequest::OutputType swift::evaluateOrFatal<swift::IRGenRequest>(swift::Evaluator&, swift::IRGenRequest)::'lambda'()>(swift::IRGenRequest const&, swift::IRGenRequest::OutputType swift::evaluateOrFatal<swift::IRGenRequest>(swift::Evaluator&, swift::IRGenRequest)::'lambda'()) + 212
16 swift-frontend           0x00000001051b99e4 swift::performIRGeneration(swift::FileUnit*, swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::StringRef, swift::PrimarySpecificPaths const&, llvm::StringRef, llvm::GlobalVariable**) + 208
17 swift-frontend           0x0000000104cc9f58 generateIR(swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, swift::PrimarySpecificPaths const&, llvm::StringRef, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, llvm::GlobalVariable*&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>) + 156
18 swift-frontend           0x0000000104cc6204 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 1416
19 swift-frontend           0x0000000104cc5664 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 656
20 swift-frontend           0x0000000104cd698c withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
21 swift-frontend           0x0000000104cc7cc4 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 708
22 swift-frontend           0x0000000104cc6c30 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2376
23 swift-frontend           0x0000000104ae0c2c swift::mainEntry(int, char const**) + 3096
24 dyld                     0x000000019c05e0e0 start + 2360
Command SwiftCompile failed with a nonzero exit code
```

</details>

**Comment by groue** [comment]
Fixed in Xcode 16.0 beta (16A5171c).
